"""empty message

Revision ID: 539d495c5650
Revises: e4bd0037f09a
Create Date: 2020-04-15 01:12:59.626417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '539d495c5650'
down_revision = 'e4bd0037f09a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
