"""empty message

Revision ID: 599e5ca7d1dc
Revises: 
Create Date: 2020-04-15 00:40:09.763730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '599e5ca7d1dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('biography', sa.Text(), nullable=True))
    op.add_column('user_profiles', sa.Column('created_on', sa.Date(), nullable=True))
    op.add_column('user_profiles', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('user_profiles', sa.Column('gender', sa.String(length=16), nullable=True))
    op.add_column('user_profiles', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('user_profiles', sa.Column('profilePic', sa.String(length=255), nullable=True))
    op.drop_constraint('user_profiles_username_key', 'user_profiles', type_='unique')
    op.drop_column('user_profiles', 'password')
    op.drop_column('user_profiles', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_unique_constraint('user_profiles_username_key', 'user_profiles', ['username'])
    op.drop_column('user_profiles', 'profilePic')
    op.drop_column('user_profiles', 'location')
    op.drop_column('user_profiles', 'gender')
    op.drop_column('user_profiles', 'email')
    op.drop_column('user_profiles', 'created_on')
    op.drop_column('user_profiles', 'biography')
    # ### end Alembic commands ###
